### ISSUE TITLE
Can you put the license on top of the file?

### ISSUE THREAD

**Issue by coldfix** [ninjaaron/fast-entry_points#4]
Hey,

- your license states that the license must be retained in all redistributions.
- you encourage to include the module into other projects as a single file

this would be easier if you add the license to the top of the module, so there is no need to worry whether one has to manually paste it there or whether one should put the script with its license file in a separate subdirectory or whatever :)

Best, and thanks for consideration,
Thomas

**Comment by ninjaaron** [comment]
Will do, first thing tomorrow!

**Comment by ninjaaron** [comment]
Done! https://github.com/ninjaaron/fast-entry_points/commit/3add046ee98947373338277da0326b0b88264a07

**Comment by coldfix** [comment]
Yay, thanks:)!

**Comment by yegorich** [comment]
@ninjaaron could you please include `LICENSE` into the PyPI's tar.gz file? Thanks
